// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {proto} from '../models';

export function Parse(arg1:Array<string>):Promise<Array<proto.File>>;
