// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {client} from '../models';

export function OpenIncludeDir():Promise<main.R>;

export function OpenProto():Promise<main.R>;

export function ParseProto(arg1:Array<string>,arg2:Array<string>):Promise<main.R>;

export function Send(arg1:client.RequestData):Promise<main.R>;

export function Stop(arg1:string):Promise<main.R>;
