// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenIncludeDir() {
  return window['go']['main']['Api']['OpenIncludeDir']();
}

export function OpenProto() {
  return window['go']['main']['Api']['OpenProto']();
}

export function ParseProto(arg1, arg2) {
  return window['go']['main']['Api']['ParseProto'](arg1, arg2);
}

export function Send(arg1) {
  return window['go']['main']['Api']['Send'](arg1);
}

export function Stop(arg1) {
  return window['go']['main']['Api']['Stop'](arg1);
}
