// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';

export function ImportFile():Promise<Array<string>>;

export function Send(arg1:types.RequestData):Promise<types.ResponseData>;
