// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ImportFile() {
  return window['go']['main']['Parser']['ImportFile']();
}

export function Parse(arg1) {
  return window['go']['main']['Parser']['Parse'](arg1);
}
