// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ImportFile():Promise<Array<string>>;

export function Parse(arg1:Array<string>):Promise<Array<main.File>>;
