// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';
import {client} from '../models';

export function OpenProto():Promise<api.R>;

export function ParseProto(arg1:Array<string>,arg2:Array<string>):Promise<api.R>;

export function Send(arg1:client.RequestData):Promise<api.R>;

export function Stop(arg1:string):Promise<api.R>;
