// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenProto() {
  return window['go']['api']['Api']['OpenProto']();
}

export function ParseProto(arg1, arg2) {
  return window['go']['api']['Api']['ParseProto'](arg1, arg2);
}
