// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';

export function OpenProto():Promise<api.R>;

export function ParseProto(arg1:Array<string>,arg2:Array<string>):Promise<api.R>;
